/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication1.connection;
import javax.swing.JFrame;
/**
 *
 * @author Pc
 */
public class Add_condicteur extends javax.swing.JFrame {

   
    /**
     * Creates new form Add_condicteur
     */
    public Add_condicteur() {
        initComponents();
        try {
            connection connect = new connection();
            connect.connectionDb();
          

        connect.myRes = connect.myst.executeQuery("select * from persone");
            while(connect.myRes.next()){
                String id = String.valueOf(connect.myRes.getString("id"));
                String nom = String.valueOf(connect.myRes.getString("nom"));
                String prenom = String.valueOf(connect.myRes.getString("prenom"));
                String login = String.valueOf(connect.myRes.getString("login"));
                String password = String.valueOf(connect.myRes.getString("password"));
                String role = String.valueOf(connect.myRes.getString("role"));

                String tbData[] = {id, nom, prenom, login, password, role};
           
            }
             } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nom_Con = new javax.swing.JTextField();
        Pre_Con = new javax.swing.JTextField();
        Log_Con = new javax.swing.JTextField();
        Psw_Con = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        is_admin = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("précédent");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 40, 90, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 140, 40, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Prénom");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 190, 60, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Login");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 240, 50, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 290, 70, 20);

        Nom_Con.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Nom_Con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_ConActionPerformed(evt);
            }
        });
        getContentPane().add(Nom_Con);
        Nom_Con.setBounds(160, 140, 150, 30);

        Pre_Con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pre_ConActionPerformed(evt);
            }
        });
        getContentPane().add(Pre_Con);
        Pre_Con.setBounds(160, 190, 150, 30);

        Log_Con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_ConActionPerformed(evt);
            }
        });
        getContentPane().add(Log_Con);
        Log_Con.setBounds(160, 240, 150, 30);
        getContentPane().add(Psw_Con);
        Psw_Con.setBounds(160, 290, 150, 30);

        jLabel8.setText("Administrateur");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 340, 70, 20);

        is_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                is_adminActionPerformed(evt);
            }
        });
        getContentPane().add(is_admin);
        is_admin.setBounds(170, 340, 20, 20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 370, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/bg3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nom_ConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_ConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_ConActionPerformed

    private void Pre_ConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pre_ConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pre_ConActionPerformed

    private void Log_ConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_ConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Log_ConActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
       
       String isSelected = "0";
       if(is_admin.isSelected()){
          isSelected ="1";
       }
       else{
       isSelected="0";
       }
         try {
                 connection connect = new connection();
                    connect.connectionDb();
                    String sql = "INSERT INTO `persone`(`nom`,'prenom','login','password','role') VALUES (?,?,?,?,?)";
 
                    PreparedStatement statement = connect.myconnection.prepareStatement(sql);
                    statement.setString(1, Nom_Con.getText());
                    statement.setString(2, Pre_Con.getText());
                    statement.setString(3, Log_Con.getText());
                    statement.setString(4, Psw_Con.getText());
                    statement.setString(5,isSelected);
                    int rowsInserted = statement.executeUpdate();
                    if (rowsInserted > 0) {
                        Condicteur cond = new Condicteur();
                        double height = cond.getHeight();
                             double width = cond.getWidth();
                             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                                double widthscreen = screenSize.getWidth();               
                                double heightscreen = screenSize.getHeight();



                             int north =  (int)((widthscreen - width)/2);             
                             int heightMiddel =  (int)((heightscreen - height)/2);

                             cond.setLocation(north, heightMiddel);

                        cond.setVisible(true);
                        this.dispose();
                    }
            
              
            } catch (SQLException ex) {
                Logger.getLogger(Add_condicteur.class.getName()).log(Level.SEVERE, null, ex);
            }
        
                                        

        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         Condicteur cond = new Condicteur();
        double height = cond.getHeight();
             double width = cond.getWidth();
             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                double widthscreen = screenSize.getWidth();               
                double heightscreen = screenSize.getHeight();

             
            
             int north =  (int)((widthscreen - width)/2);             
             int heightMiddel =  (int)((heightscreen - height)/2);

             cond.setLocation(north, heightMiddel);
        
        cond.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void is_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_is_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_is_adminActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Log_Con;
    private javax.swing.JTextField Nom_Con;
    private javax.swing.JTextField Pre_Con;
    private javax.swing.JTextField Psw_Con;
    private javax.swing.JCheckBox is_admin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
