/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class Camion extends javax.swing.JFrame {
 private String id;
            private String immatriculation;
            private boolean selected;
            static JFrame f;
            
             public void setId(String id) {
        this.id = id;
    }

    public void setimmatriculation(String immatriculation) {
        this.immatriculation = immatriculation;
    }

    public String getId() {
        return id;
    }

    public String getimmatriculation() {
        return immatriculation;
    }
    /**
     * Creates new form Camion
     */
    public Camion() {
        initComponents();
        
          try {
            connection connect = new connection();
            connect.connectionDb();
          
            
            mjTable1.getTableHeader().setOpaque(false);
            mjTable1.getTableHeader().setBackground(new Color(32,136,203));
           
     
              
        connect.myRes = connect.myst.executeQuery("select * from camion");
            while(connect.myRes.next()){
                String id = String.valueOf(connect.myRes.getString("id"));
                String immatriculation = String.valueOf(connect.myRes.getString("immatriculation"));
                String mac = String.valueOf(connect.myRes.getString("mac"));
                String tbData[] = {id,immatriculation,mac};
                DefaultTableModel tblModel = (DefaultTableModel)mjTable1.getModel();
                tblModel.addRow(tbData);
            }
             } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mjTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/update.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jButton1.setText("Ajouter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/trush.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setText("précédent");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        mjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Matriculation", "Mac"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mjTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mjTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mjTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        Update_camion  c = new Update_camion(this.id,this.immatriculation);

        double height = c.getHeight();
        double width = c.getWidth();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double widthscreen = screenSize.getWidth();
        double heightscreen = screenSize.getHeight();

        int north =  (int)((widthscreen - width)/2);
        int heightMiddel =  (int)((heightscreen - height)/2);

        c.setLocation(north, heightMiddel);

        if(this.selected){

            c.setVisible(true);
            this.dispose();
        }else{
            System.out.print("Merci de selectioné....");
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        Add_camion add = new Add_camion();

        double height = add.getHeight();
        double width = add.getWidth();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double widthscreen = screenSize.getWidth();
        double heightscreen = screenSize.getHeight();

        int north =  (int)((widthscreen - width)/2);
        int heightMiddel =  (int)((heightscreen - height)/2);

        add.setLocation(north, heightMiddel);

        add.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        try {
            connection connect = new connection();
            connect.connectionDb();

            String sql = "DELETE FROM `camion` WHERE `id`= ?";

            PreparedStatement statement = connect.myconnection.prepareStatement(sql);
            statement.setString(1, this.id);

            int rowsInserted = statement.executeUpdate();

            DefaultTableModel dm = (DefaultTableModel) this.mjTable1.getModel();
            int rowCount = dm.getRowCount();
            //Remove rows one by one from the end of the table
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }

            connect.myRes = connect.myst.executeQuery("select * from camion");

            while(connect.myRes.next()){
                String id = String.valueOf(connect.myRes.getString("id"));
                String immatriculation = String.valueOf(connect.myRes.getString("immatriculation"));                
                String mac = String.valueOf(connect.myRes.getString("mac"));


                String tbData[] = {id,immatriculation,mac};
                DefaultTableModel tblModel = (DefaultTableModel)this.mjTable1.getModel();
                tblModel.addRow(tbData);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Update_camion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

        acceuil a = new acceuil();

        double height = a.getHeight();
        double width = a.getWidth();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double widthscreen = screenSize.getWidth();
        double heightscreen = screenSize.getHeight();

        int north =  (int)((widthscreen - width)/2);
        int heightMiddel =  (int)((heightscreen - height)/2);

        a.setLocation(north, heightMiddel);

        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void mjTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mjTable1MouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel model = (DefaultTableModel) mjTable1.getModel();
        int selectedrow = mjTable1.getSelectedRow();
        
        
        this.setId(model.getValueAt(selectedrow, 0).toString());        
        this.setimmatriculation( model.getValueAt(selectedrow, 1).toString());
        this.selected = true;
    }//GEN-LAST:event_mjTable1MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Camion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mjTable1;
    // End of variables declaration//GEN-END:variables
}
