/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Camion extends javax.swing.JFrame {
           private String id;
            private String immatriculation;
            private boolean selected;
            static JFrame f;
            
             public void setId(String id) {
        this.id = id;
    }

    public void setimmatriculation(String immatriculation) {
        this.immatriculation = immatriculation;
    }

    public String getId() {
        return id;
    }

    public String getimmatriculation() {
        return immatriculation;
    }
     
    /** Creates new form Camion */
    public Camion() {
    
     initComponents();
        try {
            connection connect = new connection();
            connect.connectionDb();
          
            
            jTable1.getTableHeader().setOpaque(false);
            jTable1.getTableHeader().setBackground(new Color(32,136,203));
           
     
              
        connect.myRes = connect.myst.executeQuery("select * from camion");
            while(connect.myRes.next()){
                String id = String.valueOf(connect.myRes.getString("id"));
                String immatriculation = String.valueOf(connect.myRes.getString("immatriculation"));
                
                String tbData[] = {id,immatriculation};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbData);
            }
             } catch (SQLException e) {
            System.out.println(e);
        }
    
    
    
    
    
    }
          
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(140, 200));
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jScrollPane2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "immatriculation "
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(120, 90, 510, 160);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setText("précédent");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 80, 20);

        jButton1.setText("Ajouter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(120, 50, 73, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/update.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(150, 290, 70, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/trush.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3);
        jLabel3.setBounds(530, 290, 80, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 920, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedrow = jTable1.getSelectedRow();
        
        
        this.setId(model.getValueAt(selectedrow, 0).toString());        
        this.setimmatriculation( model.getValueAt(selectedrow, 1).toString());
        this.selected = true;
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        acceuil a = new acceuil();
        
        
            double height = a.getHeight();
             double width = a.getWidth();
             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                double widthscreen = screenSize.getWidth();               
                double heightscreen = screenSize.getHeight();

             
            
             int north =  (int)((widthscreen - width)/2);             
             int heightMiddel =  (int)((heightscreen - height)/2);

             a.setLocation(north, heightMiddel);
        
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        Add_camion add = new Add_camion();
        
        
            double height = add.getHeight();
             double width = add.getWidth();
             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                double widthscreen = screenSize.getWidth();               
                double heightscreen = screenSize.getHeight();

             
            
             int north =  (int)((widthscreen - width)/2);             
             int heightMiddel =  (int)((heightscreen - height)/2);

             add.setLocation(north, heightMiddel);
        
        add.setVisible(true);
        this.dispose();
        
            
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        Update_camion  c = new Update_camion(this.id,this.immatriculation);
        
         double height = c.getHeight();
             double width = c.getWidth();
             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                double widthscreen = screenSize.getWidth();               
                double heightscreen = screenSize.getHeight();

             
            
             int north =  (int)((widthscreen - width)/2);             
             int heightMiddel =  (int)((heightscreen - height)/2);

             c.setLocation(north, heightMiddel);
            


             if(this.selected){
                  
                 c.setVisible(true);
                 this.dispose();
             }else{
                System.out.print("Merci de selectioné....");
             }
       
        

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         try {
                 connection connect = new connection();
                    connect.connectionDb();
                    
                    String sql = "DELETE FROM `camion` WHERE `id`= ?";
 
                    PreparedStatement statement = connect.myconnection.prepareStatement(sql);
                    statement.setString(1, this.id);                      
                    

                    int rowsInserted = statement.executeUpdate();
                 
                      DefaultTableModel dm = (DefaultTableModel) this.jTable1.getModel();
                      int rowCount = dm.getRowCount();
                      //Remove rows one by one from the end of the table
                      for (int i = rowCount - 1; i >= 0; i--) {
                          dm.removeRow(i);
                      }
                          
                          
                          
                    connect.myRes = connect.myst.executeQuery("select * from camion");
                   
                    while(connect.myRes.next()){
                        String id = String.valueOf(connect.myRes.getString("id"));
                        String immatriculation = String.valueOf(connect.myRes.getString("immatriculation"));

                        String tbData[] = {id,immatriculation};
                        DefaultTableModel tblModel = (DefaultTableModel)this.jTable1.getModel();
                        tblModel.addRow(tbData);
                    }
         
            
              
            } catch (SQLException ex) {
                Logger.getLogger(Update_camion.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try static {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> {
          //  new Camion().setVisible(true);
       // });
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
