/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Update_Con extends javax.swing.JFrame {
    
    private String id;
    private String nom;
    private String prénom;
    private String login;
    private String password;    
    private String cin;

        static JFrame f;
    /**
     * Creates new form acceuil
     */
        
      public Update_Con(String id, String nom,String prénom,String cin){
         initComponents();
          this.id = id;
         this.nom = nom;
         this.prénom = prénom;
         this.cin = cin;
     
          
           this.Con_name.setText(this.nom);
          this.Con_pre.setText(this.prénom);         
          this.Con_cin.setText(this.cin);

         
        
      }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Con_name = new javax.swing.JTextField();
        addcity = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Con_pre = new javax.swing.JTextField();
        Con_cin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setText("Nom");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 90, 34, 14);
        jPanel2.add(Con_name);
        Con_name.setBounds(130, 80, 180, 30);

        addcity.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        addcity.setText("Enregistrer");
        addcity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcityMouseClicked(evt);
            }
        });
        jPanel2.add(addcity);
        addcity.setBounds(200, 280, 110, 27);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("précédent");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 20, 80, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Prénom");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 140, 60, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Cin");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 200, 60, 30);

        Con_pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Con_preActionPerformed(evt);
            }
        });
        jPanel2.add(Con_pre);
        Con_pre.setBounds(130, 140, 180, 30);
        jPanel2.add(Con_cin);
        Con_cin.setBounds(130, 200, 180, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/bg3.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setFocusable(false);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, -10, 340, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        Pesonne p = new Pesonne();
        double height = p.getHeight();
             double width = p.getWidth();
             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                double widthscreen = screenSize.getWidth();               
                double heightscreen = screenSize.getHeight();

             
            
             int north =  (int)((widthscreen - width)/2);             
             int heightMiddel =  (int)((heightscreen - height)/2);

             p.setLocation(north, heightMiddel);
        
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void addcityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcityMouseClicked
        // TODO add your handling code here:
                  
            try {
                 connection connect = new connection();
                    connect.connectionDb();
                    
                    String sql = "UPDATE `persone` SET `nom`=?,`prenom`=?,`cin`=?, `role`=? WHERE `id`=?";
                    
 
                    PreparedStatement statement = connect.myconnection.prepareStatement(sql);
                     
                    statement.setString(1, Con_name.getText());
                    statement.setString(2, Con_pre.getText());
                    statement.setString(3, Con_cin.getText()); 
                     statement.setString(4 ,"0"); 
                    statement.setString(5, this.id);
                    

                    int rowsInserted = statement.executeUpdate();
                    if (rowsInserted > 0) {
                        Pesonne p = new Pesonne();
                        double height = p.getHeight();
                             double width = p.getWidth();
                             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                                double widthscreen = screenSize.getWidth();               
                                double heightscreen = screenSize.getHeight();

                             int north =  (int)((widthscreen - width)/2);             
                             int heightMiddel =  (int)((heightscreen - height)/2);

                             p.setLocation(north, heightMiddel);

                        p.setVisible(true);
                        this.dispose();
                    }
            
              
            } catch (SQLException ex) {
                Logger.getLogger(Update_Con.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_addcityMouseClicked

    private void Con_preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Con_preActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Con_preActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Con_cin;
    private javax.swing.JTextField Con_name;
    private javax.swing.JTextField Con_pre;
    private javax.swing.JButton addcity;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
